<?php /* Smarty version 2.6.18, created on 2012-05-26 14:52:08
         compiled from info.inc.tpl */

$this->_cache_serials['/www/phpcoding/120523/FileBrowserZG/lib/Smarty/template_c//%%F5^F53^F53F416B%%info.inc.tpl.inc'] = 'd146a63569fae31262c8d10b4e21e18e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('block', 'nocache', 'info.inc.tpl', 5, false),)), $this); ?>
<?php
function _smarty_tplfunc_d146a63569fae31262c8d10b4e21e18e_0(&$_smarty)
{
$_smarty->_tag_stack[] = array('nocache', array()); $_block_repeat=true;smarty_block_nocache($_smarty->_tag_stack[count($_smarty->_tag_stack)-1][1], null, $_smarty, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php echo $_smarty->_tpl_vars['cacheState']; ?>
<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_nocache($_smarty->_tag_stack[count($_smarty->_tag_stack)-1][1], $_block_content, $_smarty, $_block_repeat); }  array_pop($_smarty->_tag_stack); 
}



?>
